import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "../globals.css"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kuhn Poker",
  description: "Generated by create next app",
};

// viewport を分離して専用のエクスポートにする
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}